### ISSUE TITLE
Calculations

### ISSUE THREAD

**Issue by fauxmight** [tobixen/calendar-cli#109]
No real problem.
I'll close this "issue" in 24 hours.
I just wanted to share this with you @tobixen because you're the only person I actually "know" who also works on calendar calculations on a regular basis:

https://xkcd.com/2867/

**Comment by tobixen** [comment]
There is an xkcd for every occasion, I'm referring to xkcd quite often.  Don't know why, but haven't read it for a while :-)

**Comment by tobixen** [comment]
While I haven't been struggling a lot with date calculations, I have had a bit of it.  Time deltas are notoriously difficult.  Even comparing two timestamps to see which one comes first can be difficult ... python raising an exception because it denies comparing a date with a timestamp ... python raising an exception because one of the timestamps are with timezone information while the other isn't.  Not to forget the DST, when the time jumps backwards  and 00:45 can come both before and after 00:30.

Seconds is the easiest to work with.  A second is a very well-defined unit - and it's just to take two unix epoch timestamp and subtract them, and one gets the timedelta in seconds - since epoch is defined to be in UTC, one doesn't even need to care about timezones.  This works ... all until the timedelta happens to span a leap second, and then everything breaks together, the unix epoch does not include the leap seconds.  Oh well, luckily in the use cases I've had to deal one second off would be acceptable.  (But I've been dealing with an application counting money.  In year 2004 I said "for money we should be using fixed point, let's use an int and divide it with 100 for presentation purposes".  Someone else said "nah - let's keep it simple stupid, let's use floats".  I replied "well ... OK".  The next eight years years or so (all until I quit that job) that decision would regularly come back and haunt me).

Unfortunately, time is rarely counted in kiloseconds and megaseconds.  Well, at least hours and minutes are very well-defined, seconds can easily be converted into hours, minutes and seconds.  And even days.  There is eventually the DST thing ... it doesn't cause that much problems if the timedelta is in seconds unix time.  The unix time is in UTC.  24 hours of time passed will be counted as 24 hours, and everyone would agree that 24 hours is 24 hours.  But what if counting in days rather then hours?  One day is 24 hours ... or is it more correct to say that one day is 23/25 hours if it happens when the DST goes into or out of effect?  I think that "in one day" should mean the same clock hours the next day ... so then the "day" is not very well-defined anymore ...

... and then things just keeps getting worse when the concepts of "month" and "year" is to be explored.  Not to forget all the weird corner cases, like when the time delta passes different time zones (i.e. during a plane journey), weird timezone changes, dateline, +++

**Comment by fauxmight** [comment]
Yep.

Ran into all of those matters (including correcting for time zones) fighting to proper calculate display of events on this project: https://codeberg.org/fauxmight/reticuldated

All I could ever think was, "I'm glad I'm working in python. I would hate to be handling this in C."
