### ISSUE TITLE
Checking for conflicts before adding an event.

### ISSUE THREAD

**Issue by rongten** [tobixen/calendar-cli#29]
Hello,
 it seems (at least on my setup) that I can add an event two times without any raised issue (with SOGo 3.2.7). Would it be possible to have an option to check for conflicts and return an error message/code in that case?

**Comment by tobixen** [comment]
I see two things here:

* Simple duplicate handling.  I'm not sure this is well thought through, but an option would maybe be to let the uuid be deterministic, based on the inputs, and leave duplication control to the server.
* Protection against double-bookings.  I see this as a useful feature in calendar-cli.  The "normal" user behaviour would be to first check the calendar to see that there aren't any conflicting events on the calendar, and then add the new event - however, it may be more efficient to specify something like --check-conflict.  If the new event overlaps with some existing event, instead of adding it to the calendar, an error is thrown informing about the double-booking.  With a --interactive option the user would interactively be asked to (1) leave calendar as it is, (2) add new event regardless of the overlap, (3) cancel the existing event and add the new.

What are your thoughts?

**Comment by tobixen** [comment]
Closing issue due to lack of feedback

**Comment by tobixen** [comment]
That's maybe a bit too passive.  Duplication prevention and protection against double bookings could be useful.  I'll raise it as two separate issues
