### ISSUE TITLE
How to pull UID of future events?

### ISSUE THREAD

**Issue by Sladur23** [tobixen/calendar-cli#93]
Hi,

I'm trying to build a script that accumulates twitch streaming schedules and displays them in separate calendars for each streamer.
To update the schedules I need to delete all future events in a given calendar and import the ical-file I get via twitchs api.

Right now I'm struggling to delete all future events in a calendar given my inability to display the UIDs of upcoming events.

How do I do this?

It might be even more streamlined to allow wildcards "*" as for example gcalcli does. There I could just go "gcalcli delete CALENDARNAME *" to delete all upcoming events in the given calendar.

**Comment by tobixen** [comment]
Perhaps it would be better to use the python caldav library directly instead of the calendar-cli?

I'm working on a new version which should make it easy to delete all future events in one command, until then it's needed to hack up something, first print out the uuids (using the templating option) and then iterate over the uuids and delete them.  I can come up with an example later perhaps, I'm too busy right now.

**Comment by Sladur23** [comment]
Firstly thank you very much for your swift response. But please do not trouble yourself. It's not that urgent and if I do not find a way right now, I will simply wait for 1.0.
